# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Slayug
description:  Currently Erasmus Student in Cluj-napoca
            First year of master degree in computer science, aim PHD
            else, i like make usefull javascript, java program, or simply funny things. PokemonGo.
baseurl: "http://slayug.fr" # the subpath of your site, e.g. /blog
url: "http://slayug.fr" # the base hostname & protocol for your site
twitter_username: Zibungass
github_username:  Slayug

# Build settings
markdown: kramdown
collections:
  projects:
    output: true
